version: '3'

services:
    jupyter:
        container_name: jupyter-ml
        build:
            context: .
            dockerfile: jupyter.dockerfile
            args:
                - ALTAIR_VERSION=2.2.2
                - BQPLOT_VERSION=0.11.2
                - BQPLOT_NPM_VERSION=0.4.3
                - EARTHENGINE_API_VERSION=0.1.152
                - GOOGLE_API_PYTHON_VERSION=1.7.4
                - IPYLEAFLET_VERSION=0.9.1
                - IPYVOLUME_VERSION=0.5.1
                - THREEJS_VERSION=2.0.3
                - WIDGETS_JUPYTERLAB_MANAGER_VERSION=0.38.1
                - NBDIME_VERSION=1.0.3
                - PALETTABLE_VERSION=3.1.1
                - PYDRIVE_VERSION=1.3.1
                - TENSORFLOW_VERSION=1.11.0
                - VEGA_DATASETS_VERSION=0.5.0
        environment:
            - JUPYTER_LAB_ENABLE=yes
            - GRANT_SUDO="yes"
        volumes:
            - ../projects:/home/jovyan/work
        ports:
            - "8888:8888"
        command: start.sh jupyter lab